export default {
    gray: {
        '50': 'oklch(from var(--rad-ui-color-gray-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-gray-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-gray-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-gray-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-gray-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-gray-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-gray-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-gray-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-gray-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-gray-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-gray-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-gray-1000) l c h / <alpha-value>)'
    },
    mauve: {
        '50': 'oklch(from var(--rad-ui-color-mauve-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-mauve-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-mauve-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-mauve-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-mauve-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-mauve-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-mauve-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-mauve-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-mauve-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-mauve-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-mauve-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-mauve-1000) l c h / <alpha-value>)'
    },
    slate: {
        '50': 'oklch(from var(--rad-ui-color-slate-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-slate-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-slate-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-slate-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-slate-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-slate-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-slate-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-slate-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-slate-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-slate-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-slate-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-slate-1000) l c h / <alpha-value>)'
    },
    sage: {
        '50': 'oklch(from var(--rad-ui-color-sage-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-sage-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-sage-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-sage-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-sage-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-sage-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-sage-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-sage-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-sage-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-sage-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-sage-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-sage-1000) l c h / <alpha-value>)'
    },
    olive: {
        '50': 'oklch(from var(--rad-ui-color-olive-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-olive-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-olive-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-olive-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-olive-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-olive-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-olive-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-olive-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-olive-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-olive-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-olive-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-olive-1000) l c h / <alpha-value>)'
    },
    sand: {
        '50': 'oklch(from var(--rad-ui-color-sand-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-sand-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-sand-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-sand-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-sand-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-sand-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-sand-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-sand-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-sand-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-sand-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-sand-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-sand-1000) l c h / <alpha-value>)'
    },
    tomato: {
        '50': 'oklch(from var(--rad-ui-color-tomato-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-tomato-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-tomato-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-tomato-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-tomato-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-tomato-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-tomato-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-tomato-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-tomato-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-tomato-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-tomato-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-tomato-1000) l c h / <alpha-value>)'
    },
    red: {
        '50': 'oklch(from var(--rad-ui-color-red-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-red-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-red-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-red-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-red-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-red-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-red-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-red-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-red-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-red-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-red-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-red-1000) l c h / <alpha-value>)'
    },
    ruby: {
        '50': 'oklch(from var(--rad-ui-color-ruby-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-ruby-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-ruby-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-ruby-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-ruby-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-ruby-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-ruby-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-ruby-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-ruby-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-ruby-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-ruby-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-ruby-1000) l c h / <alpha-value>)'
    },
    crimson: {
        '50': 'oklch(from var(--rad-ui-color-crimson-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-crimson-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-crimson-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-crimson-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-crimson-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-crimson-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-crimson-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-crimson-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-crimson-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-crimson-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-crimson-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-crimson-1000) l c h / <alpha-value>)'
    },
    pink: {
        '50': 'oklch(from var(--rad-ui-color-pink-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-pink-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-pink-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-pink-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-pink-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-pink-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-pink-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-pink-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-pink-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-pink-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-pink-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-pink-1000) l c h / <alpha-value>)'
    },
    plum: {
        '50': 'oklch(from var(--rad-ui-color-plum-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-plum-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-plum-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-plum-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-plum-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-plum-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-plum-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-plum-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-plum-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-plum-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-plum-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-plum-1000) l c h / <alpha-value>)'
    },
    purple: {
        '50': 'oklch(from var(--rad-ui-color-purple-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-purple-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-purple-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-purple-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-purple-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-purple-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-purple-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-purple-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-purple-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-purple-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-purple-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-purple-1000) l c h / <alpha-value>)'
    },
    violet: {
        '50': 'oklch(from var(--rad-ui-color-violet-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-violet-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-violet-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-violet-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-violet-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-violet-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-violet-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-violet-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-violet-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-violet-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-violet-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-violet-1000) l c h / <alpha-value>)'
    },
    iris: {
        '50': 'oklch(from var(--rad-ui-color-iris-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-iris-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-iris-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-iris-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-iris-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-iris-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-iris-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-iris-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-iris-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-iris-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-iris-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-iris-1000) l c h / <alpha-value>)'
    },
    indigo: {
        '50': 'oklch(from var(--rad-ui-color-indigo-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-indigo-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-indigo-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-indigo-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-indigo-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-indigo-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-indigo-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-indigo-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-indigo-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-indigo-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-indigo-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-indigo-1000) l c h / <alpha-value>)'
    },
    blue: {
        '50': 'oklch(from var(--rad-ui-color-blue-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-blue-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-blue-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-blue-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-blue-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-blue-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-blue-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-blue-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-blue-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-blue-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-blue-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-blue-1000) l c h / <alpha-value>)'
    },
    cyan: {
        '50': 'oklch(from var(--rad-ui-color-cyan-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-cyan-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-cyan-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-cyan-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-cyan-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-cyan-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-cyan-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-cyan-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-cyan-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-cyan-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-cyan-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-cyan-1000) l c h / <alpha-value>)'
    },
    teal: {
        '50': 'oklch(from var(--rad-ui-color-teal-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-teal-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-teal-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-teal-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-teal-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-teal-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-teal-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-teal-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-teal-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-teal-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-teal-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-teal-1000) l c h / <alpha-value>)'
    },
    jade: {
        '50': 'oklch(from var(--rad-ui-color-jade-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-jade-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-jade-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-jade-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-jade-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-jade-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-jade-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-jade-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-jade-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-jade-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-jade-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-jade-1000) l c h / <alpha-value>)'
    },
    green: {
        '50': 'oklch(from var(--rad-ui-color-green-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-green-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-green-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-green-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-green-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-green-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-green-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-green-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-green-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-green-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-green-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-green-1000) l c h / <alpha-value>)'
    },
    grass: {
        '50': 'oklch(from var(--rad-ui-color-grass-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-grass-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-grass-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-grass-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-grass-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-grass-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-grass-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-grass-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-grass-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-grass-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-grass-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-grass-1000) l c h / <alpha-value>)'
    },
    brown: {
        '50': 'oklch(from var(--rad-ui-color-brown-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-brown-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-brown-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-brown-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-brown-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-brown-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-brown-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-brown-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-brown-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-brown-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-brown-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-brown-1000) l c h / <alpha-value>)'
    },
    bronze: {
        '50': 'oklch(from var(--rad-ui-color-bronze-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-bronze-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-bronze-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-bronze-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-bronze-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-bronze-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-bronze-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-bronze-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-bronze-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-bronze-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-bronze-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-bronze-1000) l c h / <alpha-value>)'
    },
    gold: {
        '50': 'oklch(from var(--rad-ui-color-gold-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-gold-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-gold-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-gold-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-gold-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-gold-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-gold-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-gold-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-gold-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-gold-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-gold-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-gold-1000) l c h / <alpha-value>)'
    },
    sky: {
        '50': 'oklch(from var(--rad-ui-color-sky-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-sky-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-sky-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-sky-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-sky-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-sky-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-sky-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-sky-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-sky-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-sky-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-sky-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-sky-1000) l c h / <alpha-value>)'
    },
    mint: {
        '50': 'oklch(from var(--rad-ui-color-mint-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-mint-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-mint-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-mint-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-mint-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-mint-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-mint-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-mint-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-mint-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-mint-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-mint-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-mint-1000) l c h / <alpha-value>)'
    },
    lime: {
        '50': 'oklch(from var(--rad-ui-color-lime-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-lime-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-lime-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-lime-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-lime-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-lime-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-lime-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-lime-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-lime-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-lime-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-lime-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-lime-1000) l c h / <alpha-value>)'
    },
    yellow: {
        '50': 'oklch(from var(--rad-ui-color-yellow-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-yellow-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-yellow-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-yellow-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-yellow-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-yellow-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-yellow-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-yellow-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-yellow-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-yellow-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-yellow-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-yellow-1000) l c h / <alpha-value>)'
    },
    amber: {
        '50': 'oklch(from var(--rad-ui-color-amber-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-amber-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-amber-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-amber-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-amber-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-amber-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-amber-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-amber-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-amber-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-amber-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-amber-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-amber-1000) l c h / <alpha-value>)'
    },
    orange: {
        '50': 'oklch(from var(--rad-ui-color-orange-50) l c h / <alpha-value>)',
        '100': 'oklch(from var(--rad-ui-color-orange-100) l c h / <alpha-value>)',
        '200': 'oklch(from var(--rad-ui-color-orange-200) l c h / <alpha-value>)',
        '300': 'oklch(from var(--rad-ui-color-orange-300) l c h / <alpha-value>)',
        '400': 'oklch(from var(--rad-ui-color-orange-400) l c h / <alpha-value>)',
        '500': 'oklch(from var(--rad-ui-color-orange-500) l c h / <alpha-value>)',
        '600': 'oklch(from var(--rad-ui-color-orange-600) l c h / <alpha-value>)',
        '700': 'oklch(from var(--rad-ui-color-orange-700) l c h / <alpha-value>)',
        '800': 'oklch(from var(--rad-ui-color-orange-800) l c h / <alpha-value>)',
        '900': 'oklch(from var(--rad-ui-color-orange-900) l c h / <alpha-value>)',
        '950': 'oklch(from var(--rad-ui-color-orange-950) l c h / <alpha-value>)',
        '1000': 'oklch(from var(--rad-ui-color-orange-1000) l c h / <alpha-value>)'
    },
    black: 'oklch(from var(--rad-ui-color-black) l c h / <alpha-value>)',
    white: 'oklch(from var(--rad-ui-color-white) l c h / <alpha-value>)'
};
