name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Explicitly declare permissions (security best practice)
permissions:
  contents: read
  pull-requests: read

# Prevent multiple workflow runs from racing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        continue-on-error: false

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false
