name: 'Chromatic Deployment'

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]

jobs:
  chromatic-deployment:
    # Run on main repo pushes or when PR has "deploy-storybook" label
    if: github.repository == 'rad-ui/ui' && (github.event_name == 'push' || github.event.label.name == 'deploy-storybook')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Chromatic to retrieve git history

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust this to your project's Node.js version

      - name: Install dependencies
        run: npm ci  # Use 'yarn install --frozen-lockfile' if you use Yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Optional: Add any additional Chromatic CLI flags here
          # For example: --exit-zero-on-changes